"""Adding tables with Backref

Revision ID: bbafc5e64b7
Revises: 5979861082d5
Create Date: 2013-05-07 22:29:17.287823

"""

# revision identifiers, used by Alembic.
revision = 'bbafc5e64b7'
down_revision = '5979861082d5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('yer_es', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=255), nullable=False),
    sa.Column('reg_adr', sa.String(length=255), nullable=False),
    sa.Column('cor_adr', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_des', sa.String(length=255), nullable=False),
    sa.Column('icare_phone', sa.Integer(), nullable=False),
    sa.Column('icare_mobile', sa.Integer(), nullable=False),
    sa.Column('icare_fax', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('icare_email', sa.String(length=255), nullable=False),
    sa.Column('social', sa.Boolean(), nullable=True),
    sa.Column('skills_based', sa.Boolean(), nullable=True),
    sa.Column('micro', sa.Boolean(), nullable=True),
    sa.Column('areaofwork', sa.String(length=255), nullable=True),
    sa.Column('community', sa.Boolean(), nullable=True),
    sa.Column('intl_camp', sa.Boolean(), nullable=True),
    sa.Column('dis_hr', sa.Boolean(), nullable=True),
    sa.Column('dis_stationary', sa.Boolean(), nullable=True),
    sa.Column('dis_software', sa.Boolean(), nullable=True),
    sa.Column('dis_hardware', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('focus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_name', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_focus',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('focus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['focus_id'], ['focus.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('user_focus',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('focus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['focus_id'], ['focus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.add_column(u'user', sa.Column('college', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('date_of_birth', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('disaster', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('organ', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('blood_group', sa.String(length=5), nullable=False))
    op.add_column(u'user', sa.Column('twitter', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('linkedin', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('branch', sa.String(length=60), nullable=False))
    op.add_column(u'user', sa.Column('phone', sa.Integer(), nullable=False))
    op.add_column(u'user', sa.Column('google', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('facebook', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('blood', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('year_of_study', sa.Integer(), nullable=False))
    op.add_column(u'user', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column(u'user', sa.Column('pintrest', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('news', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('role', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column(u'user', u'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column(u'name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column(u'user', 'email')
    op.drop_column(u'user', 'role')
    op.drop_column(u'user', 'news')
    op.drop_column(u'user', 'pintrest')
    op.drop_column(u'user', 'address')
    op.drop_column(u'user', 'year_of_study')
    op.drop_column(u'user', 'blood')
    op.drop_column(u'user', 'facebook')
    op.drop_column(u'user', 'google')
    op.drop_column(u'user', 'phone')
    op.drop_column(u'user', 'branch')
    op.drop_column(u'user', 'linkedin')
    op.drop_column(u'user', 'twitter')
    op.drop_column(u'user', 'blood_group')
    op.drop_column(u'user', 'organ')
    op.drop_column(u'user', 'disaster')
    op.drop_column(u'user', 'date_of_birth')
    op.drop_column(u'user', 'last_name')
    op.drop_column(u'user', 'first_name')
    op.drop_column(u'user', 'college')
    op.drop_table('user_focus')
    op.drop_table('org_focus')
    op.drop_table('focus')
    op.drop_table('organisation')
    ### end Alembic commands ###
